version: '3.8'

services:
  addressmanager-app:
    build: .
    ports:
      - "5000"
    environment:
      - MONGO_URI=mongodb+srv://Madhu:1234@cluster0.yhb6mpn.mongodb.net/Address_Manager?retryWrites=true&w=majority
    depends_on:
      - db

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=Address_Manager
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  nginx:
    image: nginx:latest
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - addressmanager-app
    ports:
        - "80:80"

